### ISSUE TITLE
Doesn't work inside structures

### ISSUE THREAD

**Issue by REHvision** [sylvainjule/kirby-locator#13]
![bildschirmfoto von 2018-12-05 17-12-19](https://user-images.githubusercontent.com/2584674/49527191-a4a55a80-f8b1-11e8-83cc-337b91554f32.png)

The red bar should be the locator field.
When I decrease the indentation of the exact same field (to lift it out of the structure field) it displays and works as expected.

**Comment by sylvainjule** [comment]
Hmm, no clue why. I'll look into it!

**Comment by REHvision** [comment]
Thanks :smiley: also for making this nice plugin available in the first place!

**Comment by sylvainjule** [comment]
Glad it's useful! Should be fixed ✅
