### ISSUE TITLE
Hide map?

### ISSUE THREAD

**Issue by louiswalch** [sylvainjule/kirby-locator#14]
It would be handy to have an option to hide the map after the location has been assigned. It takes up quite a bit of room and is only needed the first time you use the field.

**Comment by sylvainjule** [comment]
That was also my thought, after using it in a few projects. It's now fixed with a new collapsed view:

![Screen Recording 2019-03-18 at 10 25 PM](https://user-images.githubusercontent.com/14079751/54566670-d5794d80-49d1-11e9-9308-f44770354c4e.gif)
