### ISSUE TITLE
Follow the composer instructions

### ISSUE THREAD

**Issue by chpio** [sylvainjule/kirby-locator#15]
Hi,

please follow the kirby composer instructions

> Both the type field and the getkirby/composer-installer dependency are required for your plugin to work, otherwise it won't be loaded correctly by Kirby.

> The setup with a separate config.php file for Composer is no longer recommended as it can cause issues with the autoloading order. If you put your code directly into the index.php file and don't autoload it with Composer, Kirby will pick it up just fine.

https://getkirby.com/docs/guide/plugins/plugin-setup-basic#the-composer-json

----

Also what's the purpose of adding the `vendor` dir to git?

**Comment by sylvainjule** [comment]
I am aware of the pluginkit and am trying to find some time to update my plugins accordingly. I am just missing some time at the moment. Any PR is welcome, else I am trying to get on it quickly.

The vendor folder, in this configuration, allows to clone / copy-paste the repo without the need of composer. But it's an outdated structure, judging from what Lukas put together.

**Comment by sylvainjule** [comment]
The plugin is now up to date ✅

**Comment by chpio** [comment]
nice, thank you

i think there is a copy & paste bug

```json
   "extra": {
        "installer-name": "superplugin"
    }
```

should be not in the config, it's purpose is to override the name of the plugin, so your plugins name gets overridden to "superplugin" right now.

**Comment by sylvainjule** [comment]
Duh, did it too quickly 🙉
That's fixed.
