### ISSUE TITLE
composer installation fails

### ISSUE THREAD

**Issue by MathiasGmeiner** [sylvainjule/kirby-locator#2]
Hi! I tried to install it with `composer require sylvainjule/locator` on `dev-master 3.0.0-beta-6.17`.
But I get this error:

```
[InvalidArgumentException]
  Could not find a matching version of package sylvainjule/locator. Check the package spelling, your version constrai
  nt and that the package is available in a stability which matches your minimum-stability (beta).
```

**Comment by MathiasGmeiner** [comment]
By the way: it works great installed manually!

**Comment by bnomei** [comment]
@sylvainjule you need to set minimum stability in composer.json. like this...

https://github.com/bnomei/kirby3-random/blob/master/composer.json#L36

**Comment by sylvainjule** [comment]
Should be good now!
