### ISSUE TITLE
Problem with marker

### ISSUE THREAD

**Issue by vbadvanced** [sylvainjule/kirby-locator#29]
Marker don't show up in my locator fields!

**Comment by distantnative** [comment]
+1 on Windows Chrome (on Mac, it's fine for me)

**Comment by distantnative** [comment]
Same with Firefox on Windows. Shows broken image:
![2020-03-10 11_21_36-New trip _ Passport](https://user-images.githubusercontent.com/3788865/76303100-720ebc80-62c1-11ea-9408-228e0905fd48.png)

**Comment by sylvainjule** [comment]
I had the issue after updating Kirby in my plugin sandbox. Somehow the alias was broken.

Deleting the `media/plugins/sylvainjule/locator` folder for kirby to rebuild it again fixed it for me. 
Can you give it a shot?

**Comment by marcomezzavilla** [comment]
> I had the issue after updating Kirby in my plugin sandbox. Somehow the alias was broken.
> 
> Deleting the `media/plugins/sylvainjule/locator` folder for kirby to rebuild it again fixed it for me.
> Can you give it a shot?

Deleting the `media/plugins/sylvainjule/locator` folder has solved the problem for me too.

**Comment by sylvainjule** [comment]
Closing this then, feel free to reopen if needed.
