### ISSUE TITLE
push version to 1.x

### ISSUE THREAD

**Issue by bnomei** [sylvainjule/kirby-locator#3]
increase version to 1.x to avoid strict semantic versioning:
https://getcomposer.org/doc/articles/versions.md#caret-version-range-

otherwise upgrading will be much harder for users.
so `0.5.0` will not upgrade to `0.6.0`.
> For pre-1.0 versions it also acts with safety in mind and treats ^0.3 as >=0.3.0 <0.4.0

**Comment by sylvainjule** [comment]
👌
