### ISSUE TITLE
correct street found, but city is not saved

### ISSUE THREAD

**Issue by agloeckner** [sylvainjule/kirby-locator#34]
I had several cases where the search found the correct street with the right postal code, but for some reason the city is not being saved.

**AC**
- enter "Bleibtreustraße 33 Berlin" in search and hit locate
- all data is saved (see gif) except the city "Berlin"

![Screen Recording 2020-10-22 at 05 08 34 PM](https://user-images.githubusercontent.com/2115252/96891926-6c00d100-1489-11eb-89fc-4a655ca5f0a0.gif)

**Comment by sylvainjule** [comment]
I cannot reproduce it, your example correctly saves the city with both Nominatim + Mapbox.

Does the issue still happen on your side?

**Comment by agloeckner** [comment]
Hey! I tried it again and now it works, I didn’t change anything - strange... Nevertheless, good it works now 😊

Thanks for the awesome plugin!

Best,
Alex
