### ISSUE TITLE
Wrong links for voyager/positron

### ISSUE THREAD

**Issue by renestalder** [sylvainjule/kirby-locator#36]
In the readme where the terms of services for the different tile services are listed, positron and voyager seem to have the same link. Also, this link doesn't point to the terms of services.

As I don't know any of those services (also couldn't find voyager by searching) I can't really contribute and fix the link myself. Positron also seems to link to "carto", which I'm not even sure if this is correct.

**Comment by sylvainjule** [comment]
It is correct that they both redirect to carto.com, although they seem to have changed their website architecture. I'll update them, thanks!

**Comment by sylvainjule** [comment]
✓
