### ISSUE TITLE
lon and lat output is with comma, instead of dot

### ISSUE THREAD

**Issue by romanustin** [sylvainjule/kirby-locator#38]
When I put marker on the map, I get lon and lat with dots, like: 58.529276, 1.449215, but when I search for location and save like it's found, output is with comma for one or both, like: 58,529276, 1.449215

**Comment by oscarsmeulders** [comment]
same problem here

**Comment by sylvainjule** [comment]
Unfortunately, I can't reproduce this. Locales and commas / dots can be tricky but I've tried multiple locales / languages and always get it correctly, with a dot. What are yours?

Also, just to be sure: 
- If you place a marker manually, lat / lon are correctly saved (with dot) in your txt files
- If you search with either Nominatim or Mapbox, lat / lon are saved with commas in your txt files

Is this what is happening?

**Comment by sylvainjule** [comment]
I am closing this as I am still unable to reproduce it. Please don't hesitate to reopen if the issue still occurs.
