### ISSUE TITLE
Cannot drag map in Firefox (Windows)

### ISSUE THREAD

**Issue by bvrp** [sylvainjule/kirby-locator#41]
Map (and pointer) is not draggable in Firefox on Windows10. Works in Chrome though.

**Comment by sylvainjule** [comment]
Unfortunately I cannot reproduce, in Windows 10 + Firefox 93 through BrowserStack.

I'd say it's leaflet-related rather than this field. Is the Leaflet demo (https://leafletjs.com/) draggable with the same setup?
