### ISSUE TITLE
Drop a marker/pin manually?

### ISSUE THREAD

**Issue by alancwoo** [sylvainjule/kirby-locator#43]
I was wondering if there is any way to simply drop a pin on the map? It's somewhat related to #33 as we need to locate items that are not going to be easily geocoded. The workaround is to currently search for something in the vicinity and then drag the marker to the appropriate location.

(Thank you for this wonderful plugin!)

**Comment by sylvainjule** [comment]
I've added an option to address this, see: https://github.com/sylvainjule/kirby-locator#511-dblclick
