### ISSUE TITLE
Store `osm_id` from response

### ISSUE THREAD

**Issue by S1SYPHOS** [sylvainjule/kirby-locator#44]
~~hey there,
would you be interested in eg a field method `toLocationLink()` to get the openstreetmap node link for a given POI? or would that be something you don't deem necessary? I'd make an API call to nominatim's `reverse` function and cache the result, that's about it ..~~

~~I'd provide a PR if it's of interest, just let me know the best way to pursue this (page method, field method, etc)~~

**// Edit:**
I propose storing `osm_id` from the response you get from Nominatim, since it represents the Node ID being used in OpenStreetMap links, eg `https://openstreetmap.org/node/OSM_ID` - that would save a call to the API using `lat` / `lon` to get it ..

Cheers!

**Comment by sylvainjule** [comment]
Fixed with 5673453 ✓
