### ISSUE TITLE
Feature suggestion: Panel view to display a collection of locator-pages on a map

### ISSUE THREAD

**Issue by moevbiz** [sylvainjule/kirby-locator#48]
I've been using this plugin for a handful of sites that include, in some way or another, a collection of multiple pages with locator fields. In the frontend, all pages are output as a set of markers on a full-screen map, each having a popup or linking to a page etc.

I'd like to suggest building an "all locations"-view as an optional panel section. This could display multiple markers on a large map, each marker linking to the respective page in the panel. I know it will come in handy at least for my current/upcoming projects.

Is this something you would consider building/reviewing a pull request for? I'll be working on at least one or two map sites this year, so these projects could justify helping out with such an addition to this plugin.

**Comment by sylvainjule** [comment]
I haven't encountered the need for such a view in a project yet so I'll probably not find the time to dig into this myself in a near future, but I'd completely be open to merge a PR which adds this as an option!

**Comment by sylvainjule** [comment]
After giving it second thoughts, I will also have a use case for such a section quite soon. However, I'll also require to preview GeoJSON (for which I am currently working on a dedicated field) and coordinates of virtual pages. Not sure if it makes much sense to integrate it here, or work on a more global view (that would be also compatible with data from [kirby-map](https://github.com/youngcut/kirby-map), for example).

**Comment by moevbiz** [comment]
a separate plugin sounds like a smart idea. let me know if you decide to do this/need help/etc – i will likely have more time after summer

**Comment by sylvainjule** [comment]
Closing this in favor of a separate plugin.
