### ISSUE TITLE
Add max-height to map

### ISSUE THREAD

**Issue by medienbaecker** [sylvainjule/kirby-locator#7]
With the `50vh` height, the map seems a bit massive on larger screens. Especially in smaller columns. Maybe a `max-height` would be good?

![image](https://user-images.githubusercontent.com/7975568/48563261-385bba80-e8f4-11e8-8486-a97db7b6bf80.png)

**Comment by sylvainjule** [comment]
Definitely! Ideally I'm planning to switch from this generic height to one proportional to the map's width . 

Or having dedicated styles for columns setup. Something like:

```scss
.k-section > .k-column[data-width="1/2"] {
    .k-locator-field {
        // rules for 1/2 columns
    }
}
```

But haven't taken time to look into this yet :)

**Comment by sylvainjule** [comment]
The height is now proportional!

It'll call for some adjustments in small columns (probably better to make the map more squared in 1/3 or 1/4 columns and downscale the controls a bit), I'll implement this soon.

**Comment by medienbaecker** [comment]
You're on fire 🔥 
Looks a lot better now!

**Comment by sylvainjule** [comment]
You wouldn't say this if you'd switched it in a 1/1 column 😶

But it's a way better basis anyway!

**Comment by medienbaecker** [comment]
Who uses `1/1` columns anyway? 🤓
