### ISSUE TITLE
Address is hidden

### ISSUE THREAD

**Issue by medienbaecker** [sylvainjule/kirby-locator#8]
The `address` is hidden, no matter if I add it to the `display` list or display all as the default.

I think I found the mistake, though: https://github.com/sylvainjule/kirby-locator/blob/master/src/field/Locator.vue#L33-L36

You check if the `display` list includes `addressdetails` instead of just `address`.

**Comment by sylvainjule** [comment]
Fixed! Thanks for spotting it.
