### ISSUE TITLE
Change(able) order of info

### ISSUE THREAD

**Issue by medienbaecker** [sylvainjule/kirby-locator#9]
While you can already [change the displayed information](https://github.com/sylvainjule/kirby-locator#53-display), the order is fixed. But for German clients I would rather like to display the number **after** the street. That's how we write it. And I guess some people would like to use a completely different order.

For this you would have to change the `display.includes('address')` in your [Locator.vue](https://github.com/sylvainjule/kirby-locator/blob/master/src/field/Locator.vue#L21-L48) to a loop iterating over the `display` array.

![hausnummer](https://user-images.githubusercontent.com/7975568/48570975-f0de2a00-e905-11e8-8e86-e5428df6a5e4.gif)

**Comment by sylvainjule** [comment]
Changed, the whole table can be re-arranged!

**Comment by medienbaecker** [comment]
Wow, you're fast. I was just in the process of doing it myself but got stuck at the `lat != latitude` point 😅
